from enum import Enum


class Zones(Enum):
    TOP_LEFT_CORNER = 1
    TOP_BEHIND_NET = 2
    TOP_RIGHT_CORNER = 3
    TOP_CREASE = 5
    TOP_LEFT_CIRCLE = 7
    TOP_HASHMARKS = 8
    TOP_RIGHT_CIRCLE = 9
    TOP_LEFT_POINT = 10
    TOP_CENTRE_POINT = 11
    TOP_RIGHT_POINT = 12
    TOP_LEFT_NEUTRAL = 13
    TOP_CENTRE_NEUTRAL = 14
    TOP_RIGHT_NEUTRAL = 15
    CENTRE_ICE = 17
    BOTTOM_LEFT_NEUTRAL = 19
    BOTTOM_CENTRE_NEUTRAL = 20
    BOTTOM_RIGHT_NEUTRAL = 21
    BOTTOM_LEFT_POINT = 22
    BOTTOM_CENTRE_POINT = 23
    BOTTOM_RIGHT_POINT = 24
    BOTTOM_LEFT_CIRCLE = 25
    BOTTOM_HASHMARKS = 26
    BOTTOM_RIGHT_CIRCLE = 27
    BOTTOM_CREASE = 29
    BOTTOM_LEFT_CORNER = 31
    BOTTOM_BEHIND_NET = 32
    BOTTOM_RIGHT_CORNER = 33
